# Generated by Django 6.0.5 on 2026-08-16 14:28

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: ClassVar[list] = [
        ("organizations", "0002_rbac"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list] = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SLA_WARNING", "SLA Warning"),
                            ("SLA_BREACH", "SLA Breach"),
                            ("ESCALATION_TRIGGERED", "Escalation Triggered"),
                        ],
                        help_text="Type of notification event.",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title.", max_length=255),
                ),
                (
                    "message",
                    models.TextField(help_text="Detailed notification message."),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        help_text="Severity level of the notification.",
                        max_length=20,
                    ),
                ),
                (
                    "incident_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Related incident ID if applicable.",
                        null=True,
                    ),
                ),
                (
                    "escalation_event_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Related escalation event ID if applicable.",
                        null=True,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read.",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the notification was marked as read.",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who should receive this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("IN_APP", "In-App")],
                        help_text="Delivery channel used.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Current delivery status.",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error details if delivery failed.",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when delivery was completed.",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of delivery retry attempts."
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="The notification being delivered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "db_table": "notification_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether email notifications are enabled.",
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether in-app notifications are enabled.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization for these preferences.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns these preferences.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization"], name="notificatio_organiz_cfd0ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient"], name="notificatio_recipie_1dd18d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization", "recipient"],
                name="notificatio_organiz_f1e630_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization", "is_read"],
                name="notificatio_organiz_84249a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read"], name="notificatio_recipie_583549_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_19df93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["severity"], name="notificatio_severit_1aebd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_e4c995_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization", "recipient", "is_read"],
                name="notif_org_recipient_read_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["organization", "created_at"], name="notif_org_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification"], name="notificatio_notific_9901ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["channel"], name="notificatio_channel_b52ae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status"], name="notificatio_status_ab0dcc_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification", "status"], name="notificatio_notific_131b46_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdelivery",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel"),
                name="unique_notification_delivery_per_channel",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(
                fields=["organization", "user"], name="notificatio_organiz_b41a16_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"),
                name="unique_notification_preference_per_org_user",
            ),
        ),
    ]
