/**
 * Audit log utility functions.
 *
 * Formatting and display helpers only — never transforms backend values into
 * misleading information. All values shown are sourced directly from the
 * backend audit log contract.
 */

import {
  AUDIT_ACTION_LABELS,
  type AuditAction,
  type AuditLog,
  type AuditLogActor,
  type AuditLogChanges,
} from '../types/audit.types';

/**
 * Format an audit record timestamp (ISO 8601 from the backend) into a
 * readable local datetime string. Uses the same locale conventions as the
 * rest of the PulseDesk UI.
 */
export function formatAuditTimestamp(createdAt: string | null | undefined): string {
  if (!createdAt) return 'N/A';

  const date = new Date(createdAt);
  if (Number.isNaN(date.getTime())) return createdAt;

  return date.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    second: '2-digit',
    hour12: true,
  });
}

/**
 * Relative timestamp for list rows ("just now", "2d ago").
 */
export function formatAuditRelativeTime(createdAt: string | null | undefined): string {
  if (!createdAt) return 'N/A';

  const date = new Date(createdAt);
  if (Number.isNaN(date.getTime())) return createdAt;

  const diffMs = Date.now() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) return 'Just now';
  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;

  return formatAuditTimestamp(createdAt);
}

/**
 * Human-readable label for an audit action value.
 * Falls back to the raw backend value when the codename is unknown so the
 * UI never fabricates a label for a backend action it does not know.
 */
export function getAuditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action as AuditAction] ?? action;
}

/**
 * Display name for an actor, or "System" for system-generated events.
 * Backend actor is null for SLA monitor / escalation engine events.
 */
export function formatActorName(actor: AuditLogActor | null): string {
  if (!actor) return 'System';

  const first = actor.first_name?.trim();
  const last = actor.last_name?.trim();

  if (first && last) return `${first} ${last}`;
  if (first) return first;
  return actor.email;
}

/**
 * Whether the audit event was generated by the system (no actor).
 */
export function isSystemEvent(log: Pick<AuditLog, 'actor'>): boolean {
  return log.actor === null;
}

/**
 * Format the client IP address for display. Returns a safe placeholder for
 * null values (backend allows null IPs).
 */
export function formatIpAddress(ip: string | null | undefined): string {
  if (!ip) return 'Unavailable';
  return ip;
}

/**
 * Format a value for a `datetime-local` input (YYYY-MM-DDTHH:mm).
 */
export function formatDateForInput(isoString: string | null | undefined): string {
  if (!isoString) return '';
  return isoString.slice(0, 16);
}

/**
 * Convert a `datetime-local` input value into an API-ready timestamp.
 * The backend's `_parse_datetime_param` accepts ISO 8601 including the bare
 * "YYYY-MM-DDTHH:mm:00" form.
 */
export function formatDateForApi(inputValue: string): string | undefined {
  if (!inputValue) return undefined;
  if (inputValue.endsWith('Z')) return inputValue;
  if (inputValue.length === 16) return `${inputValue}:00`;
  return inputValue;
}

/**
 * Title-case a backend resource type identifier for display.
 * e.g. "incident" -> "Incident", "sla_policy" -> "Sla Policy".
 * Never alters the value semantically — only presentation.
 */
export function formatResourceType(resourceType: string | null | undefined): string {
  if (!resourceType) return 'Unknown';
  return resourceType
    .split(/[_-]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Format the resource ID for display. Truncates UUIDs in compact contexts
 * while preserving the full value in the detail view.
 */
export function formatResourceId(resourceId: string | null | undefined, maxLength = 20): string {
  if (!resourceId) return '—';
  if (resourceId.length <= maxLength) return resourceId;
  return `${resourceId.slice(0, 8)}…${resourceId.slice(-4)}`;
}

/**
 * Format the safe `changes` metadata as a compact summary line.
 * Returns null when there is nothing to show so callers can omit the row.
 * The backend guarantees changes contains only safe metadata.
 */
export function summarizeChanges(changes: AuditLogChanges | null | undefined): string | null {
  if (!changes) return null;

  const entries = Object.entries(changes);
  if (entries.length === 0) return null;

  return entries
    .slice(0, 3)
    .map(([key, value]) => {
      const safeValue =
        value === null
          ? 'null'
          : typeof value === 'object'
            ? JSON.stringify(value)
            : String(value);
      return `${key}: ${safeValue}`;
    })
    .join(', ');
}