# Generated by Django 6.0.5 on 2026-08-23 12:12

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: ClassVar = [
        ("organizations", "0002_rbac"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("incident.created", "Incident Created"),
                            ("incident.updated", "Incident Updated"),
                            ("incident.status_changed", "Incident Status Changed"),
                            ("incident.priority_changed", "Incident Priority Changed"),
                            ("incident.assigned", "Incident Assigned"),
                            ("incident.resolved", "Incident Resolved"),
                            ("incident.closed", "Incident Closed"),
                            ("comment.created", "Comment Created"),
                            ("comment.updated", "Comment Updated"),
                            ("comment.deleted", "Comment Deleted"),
                            ("attachment.uploaded", "Attachment Uploaded"),
                            ("attachment.deleted", "Attachment Deleted"),
                            ("member.added", "Member Added"),
                            ("member.suspended", "Member Suspended"),
                            ("member.removed", "Member Removed"),
                            ("role.created", "Role Created"),
                            ("role.updated", "Role Updated"),
                            ("role.deleted", "Role Deleted"),
                            ("role.assigned", "Role Assigned"),
                            ("sla_policy.created", "SLA Policy Created"),
                            ("sla_policy.updated", "SLA Policy Updated"),
                            ("sla_target.created", "SLA Target Created"),
                            ("sla_target.updated", "SLA Target Updated"),
                            ("sla.breached", "SLA Breached"),
                            ("escalation_policy.created", "Escalation Policy Created"),
                            ("escalation_policy.updated", "Escalation Policy Updated"),
                            ("escalation.triggered", "Escalation Triggered"),
                        ],
                        db_index=True,
                        help_text="Stable dot-notation action identifier.",
                        max_length=80,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Class/entity type of the affected resource, e.g. 'incident'.",
                        max_length=80,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        db_index=True,
                        help_text="String representation of the affected resource's primary key.",
                        max_length=100,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Safe contextual metadata: before/after values, labels. Must never contain passwords, tokens, or secrets.",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address at the time of the action.",
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. Null for system-generated events (SLA monitor, escalation engine).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this audit record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="audit_org_created_idx",
                    ),
                    models.Index(
                        fields=["organization", "action"], name="audit_org_action_idx"
                    ),
                    models.Index(
                        fields=["organization", "resource_type", "resource_id"],
                        name="audit_org_resource_idx",
                    ),
                    models.Index(
                        fields=["organization", "actor"], name="audit_org_actor_idx"
                    ),
                ],
            },
        ),
    ]
