# Generated by Django 6.0.8 on 2026-09-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('incident.created', 'Incident Created'), ('incident.updated', 'Incident Updated'), ('incident.status_changed', 'Incident Status Changed'), ('incident.priority_changed', 'Incident Priority Changed'), ('incident.assigned', 'Incident Assigned'), ('incident.resolved', 'Incident Resolved'), ('incident.closed', 'Incident Closed'), ('comment.created', 'Comment Created'), ('comment.updated', 'Comment Updated'), ('comment.deleted', 'Comment Deleted'), ('attachment.uploaded', 'Attachment Uploaded'), ('attachment.deleted', 'Attachment Deleted'), ('member.added', 'Member Added'), ('member.suspended', 'Member Suspended'), ('member.removed', 'Member Removed'), ('role.created', 'Role Created'), ('role.updated', 'Role Updated'), ('role.deleted', 'Role Deleted'), ('role.assigned', 'Role Assigned'), ('sla_policy.created', 'SLA Policy Created'), ('sla_policy.updated', 'SLA Policy Updated'), ('sla_target.created', 'SLA Target Created'), ('sla_target.updated', 'SLA Target Updated'), ('sla.breached', 'SLA Breached'), ('escalation_policy.created', 'Escalation Policy Created'), ('escalation_policy.updated', 'Escalation Policy Updated'), ('escalation.triggered', 'Escalation Triggered'), ('settings.updated', 'Organization Settings Updated')], db_index=True, help_text='Stable dot-notation action identifier.', max_length=80),
        ),
    ]
