# Generated by Django 6.0.5 on 2026-08-23 09:32

import uuid

import attachments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # noqa: RUF012
        ("incidents", "0002_alter_incident_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename provided by the uploader (display only).",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Storage-relative path managed by Django's storage backend.",
                        upload_to=attachments.models._attachment_upload_to,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="MIME type declared and/or validated at upload time.",
                        max_length=100,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes."),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="incidents.incident",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": "attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["incident", "created_at"],
                        name="attachments_inciden_d6dcaf_idx",
                    ),
                    models.Index(
                        fields=["uploader"], name="attachments_uploade_78a2ae_idx"
                    ),
                ],
            },
        ),
    ]
