# Generated by Django 6.0.8 on 2026-08-12 07:26

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("incidents", "0001_initial"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[
                    ("P1", "P1 — Critical"),
                    ("P2", "P2 — High"),
                    ("P3", "P3 — Medium"),
                    ("P4", "P4 — Low"),
                ],
                default="P3",
                max_length=15,
            ),
        ),
    ]
