# Generated by Django 6.0.5 on 2026-08-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ("accounts", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
