# Generated by Django 6.0.5 on 2026-08-14 07:19

from typing import ClassVar

import django.utils.timezone
from django.db import migrations, models


def migrate_verified_users(apps, schema_editor):
    """Migrate existing verified users to the new email_verified_at field."""
    User = apps.get_model("accounts", "User")

    # For users who had is_verified=True, set email_verified_at to now
    # This is a safe default - existing verified users remain verified
    for user in User.objects.filter(is_verified=True):
        user.email_verified_at = django.utils.timezone.now()
        user.save(update_fields=["email_verified_at"])


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp when the user verified their email. NULL means unverified.",
                null=True,
            ),
        ),
        migrations.RunPython(migrate_verified_users, migrations.RunPython.noop),
    ]
