# Generated by Django 6.0.8 on 2026-08-12 19:01

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        ("incidents", "0002_alter_incident_priority"),
        ("organizations", "0002_rbac"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="EscalationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Only one active policy per organization may be the default. Enforced by a partial unique index.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_policies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Policy",
                "verbose_name_plural": "Escalation Policies",
                "db_table": "escalation_policies",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="EscalationLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Execution order within the policy. Must be unique per policy."
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "delay_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minutes after the breach trigger before this level becomes due.",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNEE", "Assigned Agent"),
                            ("ROLE", "Organization Role"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For ROLE targets: the Role UUID. For ASSIGNEE targets: empty (resolved at evaluation time).",
                        max_length=255,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="escalation.escalationpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Level",
                "verbose_name_plural": "Escalation Levels",
                "db_table": "escalation_levels",
                "ordering": ["policy", "level"],
            },
        ),
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("RESPONSE_BREACH", "Response SLA Breach"),
                            ("RESOLUTION_BREACH", "Resolution SLA Breach"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="escalation.escalationpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Rule",
                "verbose_name_plural": "Escalation Rules",
                "db_table": "escalation_rules",
            },
        ),
        migrations.CreateModel(
            name="IncidentEscalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("RESPONSE_BREACH", "Response SLA Breach"),
                            ("RESOLUTION_BREACH", "Resolution SLA Breach"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "current_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The level number of the last executed escalation level (0 = none yet).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="incidents.incident",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_escalations",
                        to="escalation.escalationpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Escalation",
                "verbose_name_plural": "Incident Escalations",
                "db_table": "incident_escalations",
            },
        ),
        migrations.CreateModel(
            name="EscalationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="The escalation level number that was executed."
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("RESPONSE_BREACH", "Response SLA Breach"),
                            ("RESOLUTION_BREACH", "Resolution SLA Breach"),
                        ],
                        max_length=30,
                    ),
                ),
                ("triggered_at", models.DateTimeField()),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNEE", "Assigned Agent"),
                            ("ROLE", "Organization Role"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the target at execution time (role UUID or 'assignee').",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("EXECUTED", "Executed")],
                        default="EXECUTED",
                        max_length=20,
                    ),
                ),
                (
                    "incident_escalation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="escalation.incidentescalation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Event",
                "verbose_name_plural": "Escalation Events",
                "db_table": "escalation_events",
                "ordering": ["triggered_at", "level"],
            },
        ),
        migrations.AddIndex(
            model_name="escalationpolicy",
            index=models.Index(
                fields=["organization", "is_active"],
                name="escalation__organiz_d3c155_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="escalationpolicy",
            index=models.Index(
                fields=["organization", "is_default"],
                name="escalation__organiz_63ca07_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="escalationpolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_escalation_policy_name_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="escalationpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("organization",),
                name="unique_active_default_escalation_policy_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="escalationlevel",
            index=models.Index(
                fields=["policy", "level"], name="escalation__policy__35f64d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="escalationlevel",
            constraint=models.UniqueConstraint(
                fields=("policy", "level"), name="unique_escalation_level_per_policy"
            ),
        ),
        migrations.AddIndex(
            model_name="escalationrule",
            index=models.Index(
                fields=["policy", "trigger_type"], name="escalation__policy__e7b94f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="escalationrule",
            constraint=models.UniqueConstraint(
                fields=("policy", "trigger_type"),
                name="unique_escalation_rule_per_policy_trigger",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentescalation",
            index=models.Index(
                fields=["incident"], name="incident_es_inciden_a51d51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentescalation",
            index=models.Index(
                fields=["policy"], name="incident_es_policy__bc5282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentescalation",
            index=models.Index(fields=["status"], name="incident_es_status_b8adf3_idx"),
        ),
        migrations.AddIndex(
            model_name="incidentescalation",
            index=models.Index(
                fields=["incident", "status"], name="incident_es_inciden_1bfbf6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentescalation",
            constraint=models.UniqueConstraint(
                fields=("incident", "policy", "trigger_type"),
                name="unique_incident_escalation_per_policy_trigger",
            ),
        ),
        migrations.AddIndex(
            model_name="escalationevent",
            index=models.Index(
                fields=["incident_escalation"], name="escalation__inciden_a49b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="escalationevent",
            index=models.Index(
                fields=["incident_escalation", "level"],
                name="escalation__inciden_0e0536_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="escalationevent",
            index=models.Index(
                fields=["triggered_at"], name="escalation__trigger_25c081_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="escalationevent",
            constraint=models.UniqueConstraint(
                fields=("incident_escalation", "level", "trigger_type"),
                name="unique_escalation_event_per_level_trigger",
            ),
        ),
    ]
