# Generated by Django 6.0.8 on 2026-08-12 07:26

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        ("incidents", "0002_alter_incident_priority"),
        ("organizations", "0002_rbac"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Only one active policy per organization may be the default. Enforced by a partial unique index.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_policies",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Policy",
                "verbose_name_plural": "SLA Policies",
                "db_table": "sla_policies",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncidentSLA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response_deadline", models.DateTimeField()),
                ("resolution_deadline", models.DateTimeField()),
                ("response_breached", models.BooleanField(default=False)),
                ("resolution_breached", models.BooleanField(default=False)),
                ("response_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla",
                        to="incidents.incident",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_slas",
                        to="sla.slapolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident SLA",
                "verbose_name_plural": "Incident SLAs",
                "db_table": "incident_slas",
            },
        ),
        migrations.CreateModel(
            name="SLATarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P1", "P1 — Critical"),
                            ("P2", "P2 — High"),
                            ("P3", "P3 — Medium"),
                            ("P4", "P4 — Low"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "response_time_minutes",
                    models.PositiveIntegerField(
                        help_text="Minutes until the incident must be acknowledged."
                    ),
                ),
                (
                    "resolution_time_minutes",
                    models.PositiveIntegerField(
                        help_text="Minutes until the incident must be resolved."
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="sla.slapolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Target",
                "verbose_name_plural": "SLA Targets",
                "db_table": "sla_targets",
                "ordering": ["policy", "priority"],
            },
        ),
        migrations.AddIndex(
            model_name="slapolicy",
            index=models.Index(
                fields=["organization", "is_active"],
                name="sla_policie_organiz_d8f538_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="slapolicy",
            index=models.Index(
                fields=["organization", "is_default"],
                name="sla_policie_organiz_f6bf2f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="slapolicy",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_sla_policy_name_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="slapolicy",
            # Partial unique index using Django's Q() condition.
            # Django translates this to engine-correct SQL automatically:
            #   PostgreSQL (Supabase): WHERE (is_active = TRUE AND is_default = TRUE)
            #   SQLite (tests):        WHERE ("is_active" AND "is_default")
            # This replaces the previous RunSQL which hardcoded SQLite boolean
            # literals (= 1) and would have silently produced invalid SQL on
            # PostgreSQL in production.
            constraint=models.UniqueConstraint(
                fields=("organization",),
                condition=Q(is_active=True, is_default=True),
                name="unique_active_default_sla_policy_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentsla",
            index=models.Index(
                fields=["incident"], name="incident_sl_inciden_0ea521_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentsla",
            index=models.Index(
                fields=["policy"], name="incident_sl_policy__f44f07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentsla",
            index=models.Index(
                fields=["response_deadline"], name="incident_sl_respons_29ca2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentsla",
            index=models.Index(
                fields=["resolution_deadline"], name="incident_sl_resolut_75be54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="slatarget",
            index=models.Index(
                fields=["policy", "priority"], name="sla_targets_policy__4b8e19_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="slatarget",
            constraint=models.UniqueConstraint(
                fields=("policy", "priority"),
                name="unique_sla_target_per_policy_priority",
            ),
        ),
    ]
