# Generated by Django 6.0.5 on 2026-08-24 04:07
# Phase 13.6 — Organization Settings.
# Includes a data migration that backfills default OrganizationSettings
# for every Organization that already exists.

import uuid
from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


def backfill_settings_for_existing_organizations(apps, schema_editor):
    """
    Create OrganizationSettings with defaults for every Organization that
    does not already have one.

    This runs on fresh installs (where there are no organizations yet, so
    it's a no-op) and on existing deployments where organizations were
    created before the settings subsystem was introduced.
    """
    Organization = apps.get_model("organizations", "Organization")
    OrganizationSettings = apps.get_model("settings", "OrganizationSettings")

    existing_org_ids = set(
        OrganizationSettings.objects.values_list("organization_id", flat=True)
    )
    missing = Organization.objects.exclude(id__in=existing_org_ids)

    to_create = [
        OrganizationSettings(
            organization_id=org.id,
            default_incident_priority="P3",
            default_incident_status="OPEN",
            incident_comments_enabled=True,
            notification_incident_emails_enabled=True,
            notification_escalation_emails_enabled=True,
            notification_sla_emails_enabled=True,
            sla_auto_apply_default_policy=True,
            escalation_auto_apply_default_policy=True,
        )
        for org in missing
    ]

    if to_create:
        OrganizationSettings.objects.bulk_create(to_create, batch_size=500)


def reverse_backfill(apps, schema_editor):
    """
    Reversing this migration removes all OrganizationSettings rows before
    dropping the table. The model is being removed anyway, so bulk
    deletion is safe.
    """
    OrganizationSettings = apps.get_model("settings", "OrganizationSettings")
    OrganizationSettings.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies: ClassVar = [
        ("organizations", "0002_rbac"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_incident_priority",
                    models.CharField(
                        choices=[
                            ("P1", "P1 — Critical"),
                            ("P2", "P2 — High"),
                            ("P3", "P3 — Medium"),
                            ("P4", "P4 — Low"),
                        ],
                        default="P3",
                        help_text="Default priority assigned to newly created incidents.",
                        max_length=15,
                    ),
                ),
                (
                    "default_incident_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="Default status assigned to newly created incidents.",
                        max_length=20,
                    ),
                ),
                (
                    "incident_comments_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether incident comments are enabled for this organization.",
                    ),
                ),
                (
                    "notification_incident_emails_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether incident-related notification emails are sent to organization members. In-app notifications are unaffected.",
                    ),
                ),
                (
                    "notification_escalation_emails_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether escalation-triggered notification emails are sent. In-app notifications are unaffected.",
                    ),
                ),
                (
                    "notification_sla_emails_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether SLA warning and breach notification emails are sent. In-app notifications are unaffected.",
                    ),
                ),
                (
                    "sla_auto_apply_default_policy",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the organization's default active SLA policy is automatically applied to newly created incidents.",
                    ),
                ),
                (
                    "escalation_auto_apply_default_policy",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the organization's default active escalation policy is automatically evaluated for SLA breaches.",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
                "db_table": "organization_settings",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="organizatio_organiz_423e61_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_settings_for_existing_organizations,
            reverse_backfill,
        ),
    ]
